### ISSUE TITLE
wierd crash with when opening book with client on server

### ISSUE THREAD

**Issue by SDUBZ** [Creysys/GuideBook#1]
version of guide book guide-1.0 for 1.8.9 heres the crash report that crashed me back to desktop/launcher  
[crash-2016-03-28_09.47.34-client.txt](https://github.com/Creysys/GuideBook/files/191180/crash-2016-03-28_09.47.34-client.txt)

**Comment by Creysys** [comment]
Some block or item seems to be missing a display name which i didn't check for.
This will be fixed in the next version which will be for 1.9 though so sorry for that :S

Anyways thanks for posting :)

**Comment by Creysys** [comment]
https://github.com/Creysys/GuideBook/commit/4a90029a67aa0712a2286b9149b478e457bee9cb#diff-15bd0f900eaf30bc926aed74a9a04f6aR112

**Comment by Creysys** [comment]
4a90029#diff-15bd0f900eaf30bc926aed74a9a04f6aR112
