### ISSUE TITLE
Game crashes on item right click

### ISSUE THREAD

**Issue by mycelo1** [Creysys/GuideBook#3]
Version 1.6a crashes the game when I try to see selected item's uses.

**Comment by mycelo1** [comment]
Only crashes when running along other mods. All ok then.

**Comment by Creysys** [comment]
Could you maybe add the crashlog? It shouldnt crash your game even if you're playing with other mods.

**Comment by mycelo1** [comment]
I am sorry, currently I cannot reproduce the error.

At the time I had this mod alongside BetterArmor, BetterWeapons and Optifine HD on the latest Forge. It crashed whenever I tried to view an item's uses. Viewing recipes to build that item still worked.

Now I have Optifine HD B5 and Quark beta 22. Everything working fine.

**Comment by Creysys** [comment]
Weird but ok, thanks anyways!
