### ISSUE TITLE
[1.9.4] Incompatibility with Inventory Pets (Crash)

### ISSUE THREAD

**Issue by Wisecompany** [Creysys/GuideBook#4]
Inventory Pets + Guide Book causes a crash. I don't know which mod is responsible, so I'm posting it in both Gits.

http://pastebin.com/1gY6KdWt

Inventory Pets Github issue: https://github.com/capnkirok/Inventory-Pets/issues/87

**Comment by capnkirok** [comment]
My guess is that this has to do that I have conditional recipes tied to configs. @Creysys is it possible to do a null pointer check here on your side?

**Comment by Creysys** [comment]
Sorry for the late response. Yes i will do that.

**Comment by Creysys** [comment]
Version 1.6.2 will be uploaded. But seriously who adds ItemStacks with a null item to a recipe...

**Comment by capnkirok** [comment]
Well, I have recipes hidden based on conditional configs, which I *think* causes this. I don't have any outright recipes with null item in them. Thank you!
